name: Print Repository Name

on:
  push:
  workflow_dispatch:

jobs:
  print-repo-name:
    runs-on: ubuntu-latest
    steps:
      - name: Print repository name only (without user/org)
        run: |
          echo "Repo name only: ${{ github.event.repository.name }}"